name: automerge
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
    uses: yxtay/.github/.github/workflows/automerge.yml@3162634a396310eadc5c727ec4e69345026a5f63 # main
