name: automerge
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
    uses: yxtay/.github/.github/workflows/automerge.yml@83cc447776109d6d9683ac510219d7440c0c8d03 # main
