name: automerge
on:
  pull_request:
    branches: [main]
permissions: {}
jobs:
  automerge:
    permissions:
      contents: write
      pull-requests: write
    uses: yxtay/.github/.github/workflows/automerge.yml@617d74e18c8f4dab4c527884375b11f83d57715c # main
