name: megalinter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
permissions: {}
jobs:
  megalinter:
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      statuses: write
    uses: yxtay/.github/.github/workflows/megalinter.yml@4237da10642468bb8c8b9339dc4b1986497d02b5 # main
    with:
      run-ci_light: false
      run-python: true
