name: megalinter
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
permissions: {}
jobs:
  megalinter:
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      statuses: write
    uses: yxtay/.github/.github/workflows/megalinter.yml@b4201955c6016e9f6b5c9e870cef09e84fcde9ed # main
    with:
      run-ci_light: false
      run-python: true
