name: ossf
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
permissions: {}
jobs:
  ossf:
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: yxtay/.github/.github/workflows/ossf.yml@97c3103bec97b8bc76aa7ce57f392569c822f383 # main
