name: ossf
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
permissions: {}
jobs:
  ossf:
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: yxtay/.github/.github/workflows/ossf.yml@83cc447776109d6d9683ac510219d7440c0c8d03 # main
