name: ossf
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
permissions: {}
jobs:
  ossf:
    permissions:
      contents: read
      id-token: write
      security-events: write
    uses: yxtay/.github/.github/workflows/ossf.yml@c580a2b5cdd184c3a653a6a63b6cef73daeab8ef # main
