name: pr
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
permissions: {}
jobs:
  pr:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: yxtay/.github/.github/workflows/pr.yml@c580a2b5cdd184c3a653a6a63b6cef73daeab8ef # main
