name: pr
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
permissions: {}
jobs:
  pr:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: yxtay/.github/.github/workflows/pr.yml@6db1426b042c0ac90491e8ecb91393cfe98d4db5 # main
