name: pr
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
permissions: {}
jobs:
  pr:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    uses: yxtay/.github/.github/workflows/pr.yml@0b3520b43b5cfc27053dc6b689ee2b7679c8d398 # main
