name: scans
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
permissions: {}
jobs:
  reusable:
    permissions:
      contents: write
      pull-requests: write
      security-events: write
      statuses: write
    uses: yxtay/.github/.github/workflows/scans.yml@af2afe1af9dc76d63802d1ef46a182c059f87e59 # main
    with:
      run-ci_light: false
      run-python: true
